### ISSUE TITLE
Failed to activate the atom-cfn package

### ISSUE THREAD

**Issue by pk2745** [coryforsythe/atom-cfn#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-cfn](https://github.com/coryforsythe/atom-cfn) package 1.4.0

### Stack Trace

Failed to activate the atom-cfn package

```
At ENOENT: no such file or directory, open 'C:\Users\pkumar\.aws\credentials'

Error: ENOENT: no such file or directory, open 'C:\Users\pkumar\.aws\credentials'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at Object.activate (/packages/atom-cfn/lib/main.js:22:29)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017814)
    at measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017226)
    at Package.measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3014857)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017086)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017029)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382643)
    at config.transactAsync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382259)
    at Config.transactAsync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:332443)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382209)
    at PackageManager.activate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:381827)
    at t.loadState.then (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:662772)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
ask-integration 0.1.1 
atom-cfn 1.4.0 
atom-cfn-lint 0.6.2 
atom-cform 0.6.0 
atom-cform-yaml 0.5.1-0 
file-icons 2.1.28 
file-type-icons 1.3.4 
formatter-json 1.0.1 
iam-syntax 0.1.5 
language-terraform 0.8.1 
language-yaml-cloudformation 0.3.1 
linter 2.3.0 
linter-js-cloudformation-yaml 2.2.1 
linter-package-json-validator 2.0.0 
linter-terraform-semantics 0.2.0 
linter-terraform-syntax 1.2.5 
pretty-json 2.0.3 
s3uploader 1.1.0 
terraform-fmt 0.3.0 
```

**Comment by dragonfly-net** [comment]
Need install aws for windows. Bug - package need inform about it.

**Comment by dragonfly-net** [comment]
https://docs.aws.amazon.com/en_us/cli/latest/userguide/install-windows.html
